# Generated by Django 5.2.11 on 2026-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_goal_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoney_info',
            name='payment_method',
            field=models.CharField(choices=[('Google Pay', 'Google Pay'), ('Cash', 'Cash'), ('Paytm', 'Paytm'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='addmoney_info',
            name='vat_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
