# Generated by Django 5.2.11 on 2026-03-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_reminder_status_userprofile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category'),
        ),
        migrations.DeleteModel(
            name='Addmoney_info',
        ),
    ]
